### ISSUE TITLE
ImportDecl token's range may be calculated incorrectly

### ISSUE THREAD

**Issue by wclr** [natefaubion/purescript-language-cst-parser#44]
Seems like it doesn't take into account some actual symbols inside import's statements.

Here in this an example of parsing `import A (X(..), fn)` it returns that `fn` token's start.colum is 15 though it shoulbe 17, maybe it doesn't count `..` in parens (DataMember..

For a quick test:
```purs
module TestCst where

import Prelude
import Debug (spy)
import PureScript.CST (parseImportDecl)

x = spy "parsed" $ parseImportDecl "import A (X(..), fn)"
```

Debug output:
```
      value1: ImportValue {
                value0: {
                  token: {
                    range: {
                      start: { line: 0, column: 15 },
                      end: { line: 0, column: 17 }
                    },
                    leadingComments: [],
                    trailingComments: [],
                    value: TokLowerName { value0: Nothing {}, value1: 'fn' }      
                  },
                  name: 'fn'
                }
              }
            }
```

**Comment by natefaubion** [comment]
Good catch! I think it's because this bump is wrong:
https://github.com/natefaubion/purescript-language-cst-parser/blob/6d3e406369988125107fdf1a41454c46b07412c6/src/PureScript/CST/Lexer.purs#L295-L296

`SymbolName` (which is what `(..)` is lexed as) when rendered has extra parens, which isn't accounted for here. It's only counting the length of the qualifier and the length of the symbol. Additionally:
https://github.com/natefaubion/purescript-language-cst-parser/blob/6d3e406369988125107fdf1a41454c46b07412c6/src/PureScript/CST/Lexer.purs#L297-L298

This is wrong for the same reason. The ASCII SymbolArrow is correct though.
