### ISSUE TITLE
Update package set to v0.14.0?

### ISSUE THREAD

**Issue by JordanMartinez** [natefaubion/purescript-language-cst-parser#7]
Saw this in `integration/Main.purs`:
```purescript
-- TODO: Upgrade packages ref to 0.14 package set
defaultSpagoDhall :: String
defaultSpagoDhall = Array.intercalate "\n"
  [ "{ name = \"test-parser\""
  , ", dependencies = [] : List Text"
  , ", packages = https://github.com/purescript/package-sets/releases/download/psc-0.13.8-20200922/packages.dhall sha256:5edc9af74593eab8834d7e324e5868a3d258bbab75c5531d2eb770d4324a2900"
  , ", sources = [] : List Text"
  , "}"
  ]
```
Can this be fixed now (I could submit a PR)? Or are you waiting until `v0.14.0` officially comes out?

**Comment by natefaubion** [comment]
I think we should have a default, and right now it's not super important if it's 0.13 or 0.14. It would be nice if we could take the set as a CLI argument though. `npm run parse-package-set --release psc-0.13.8-20200922` or something.

**Comment by thomashoneyman** [comment]
@colinwahl and I chose the the latest 0.13.8 package set instead of a 0.14 package because it is much larger than our existing working 0.14 package sets, and because it's stable. Once there's a sizable 0.14 package set I think we should switch to it. After all, the idea of this test is to make sure that the parser works on as many packages as possible.

I agree with @natefaubion that a CLI argument makes sense, so you can use whatever package set you want. It's possible but probably premature to introduce something like optparse to the test infrastructure; we could just parse out the node arguments.

**Comment by natefaubion** [comment]
This was already done. Not sure if we should update it again though.
